### ISSUE TITLE
ROADMAP-v2.0

### ISSUE THREAD

**Issue by llaville** [llaville/umlwriter#12]
- [X] provide a changelog for major version 2.0 (code rewrite)
- [X] drop support of PHP 5 for version 2.0
- [X] personalize the render ( something like this [project](https://github.com/Nono1971/doctrine-yuml-bundle#personalize-the-render) did )

**Comment by llaville** [comment]
- https://github.com/llaville/umlwriter/releases/tag/2.0.0-beta.1 was the first step to new architecture of version 2.0; it included support of GraphViz format
- https://github.com/llaville/umlwriter/releases/tag/2.0.0-beta.2 included support of PlantUML format

See [examples folder](https://github.com/llaville/umlwriter/tree/2.x/examples) of branch 2.x to learn how to use in batch mode.

`diagram:class` console command is able to parse one php script or a full directory (including sub-dir) and make graph statements in both GraphViz and PlantUML formats (see `--generator` option).

**Comment by llaville** [comment]
Development of new major version 2.0 is over and documentation is available at http://bartlett.laurent-laville.org/umlwriter/
First RC will come soon !

**Comment by llaville** [comment]
2.0.0-rc.1 is now available and begin the new code of master branch.

**Comment by llaville** [comment]
2.0.0-rc.2 is now available

**Comment by llaville** [comment]
Final stable release 2.0.0 is waiting a stable versions of graphp/graph and graphp/graphviz.
Others RC will be published following graphp/* packages development cycle.

**Comment by llaville** [comment]
Final stable release 2.0.0 will be published in two days (2021-12-02). I won't wait anymore for stable release of `graph/graph` and `graph/graphviz`. Projects seems at stop ! 

- I've on migration to https://github.com/Roave/BetterReflection, following recommendation we can read on latest version v2 https://github.com/goaop/parser-reflection/releases/tag/2.1.2
- One regret : PHP 8 compatibility will be not accepted due to `roave/better-reflection` v4 constraint. Will wait for major release v5 to get it back
